name: $(Build.BuildID)

trigger:
- master

resources:
- repo: self

variables:
  Folder: 'dist'
  TEAM_CIBUILD: 'true'

stages:
- stage: Build
  displayName: Build Stage

  jobs:
  - job: macOS_Linux_Phase
    displayName: 'Build'
    strategy:
      matrix:
        macOS:
          OS: 'macOS'
          vmImageName: 'macOS-latest'
        Linux:
          OS: 'Linux'
          vmImageName: 'ubuntu-latest'
      maxParallel: 2
    pool:
      vmImage: $(vmImageName)
    steps:
    - template: build/unitTests.yml
      parameters:
        os: '$(OS)'

  - job: Windows_Phase
    displayName: Build Windows
    pool:
      vmImage: 'windows-latest'

    steps:
    - template: build/unitTests.yml
      parameters:
        os: 'Windows'
        codeCoverage: 'true'

    - task: PowerShell@2
      displayName: 'Install PSScriptAnalyzer'
      inputs:
        targetType: 'inline'
        script: 'Install-Module -Name PSScriptAnalyzer -Repository PSGallery -Force -Scope CurrentUser -Verbose'

    - task: PowerShell@2
      displayName: 'Run Static Code Analysis'
      inputs:
        targetType: 'inline'
        script: |
          # Has to happen in this task for it to take effect
          # Load the psd1 file so you can read the required modules and import them
          $manifest = Import-PowerShellDataFile .\dist\*.psd1

          # Import each module
          $manifest.RequiredModules | ForEach-Object { Import-Module -Name $_ }

          $r = Invoke-ScriptAnalyzer –Path ./dist –Recurse | Where-Object severity -ne "Information"
          $r | ForEach-Object {Write-Host "##vso[task.logissue type=$($_.Severity);sourcepath=$($_.ScriptPath);linenumber=$($_.Line);columnnumber=$($_.Column);]$($_.Message)"}

    - task: CredScan@2
      displayName: 'Run CredScan'
      inputs:
        suppressionsFile: '$(Build.SourcesDirectory)/build/credscan-supression.json'

    - task: SdtReport@1
      displayName: 'Create Security Analysis Report'
      inputs:
        AllTools: true

    - task: PublishSecurityAnalysisLogs@2
      displayName: 'Publish Security Analysis Logs'

    - task: PostAnalysis@1
      displayName: 'Post Analysis'
      inputs:
        AllTools: true

    - task: CopyFiles@2
      displayName: 'Copy Module to Artifacts Folder'
      inputs:
        Contents: |
          README.md
          .gitignore
          dist\**
        TargetFolder: '$(build.artifactstagingdirectory)/VSTeam'
        flattenFolders: false
      condition: and(succeeded(), eq(variables['System.PullRequest.IsFork'], false))

    - task: PublishPipelineArtifact@1
      displayName: 'Publish Module'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/VSTeam'
        artifact: 'module'
      condition: and(succeeded(), eq(variables['System.PullRequest.IsFork'], false))

    - task: CopyFiles@2
      displayName: 'Copy Integration Tests Artifacts Folder'
      inputs:
        Contents: |
          dist\*.psd1
          integration\**
        TargetFolder: '$(build.artifactstagingdirectory)/Tests'
      condition: and(succeeded(), eq(variables['System.PullRequest.IsFork'], false))

    - task: PublishPipelineArtifact@1
      displayName: 'Publish Tests'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/Tests'
        artifact: 'test'
      condition: and(succeeded(), eq(variables['System.PullRequest.IsFork'], false))

- stage: Package
  displayName: Package Management
  dependsOn: Build
  jobs:
  - deployment: Deploy
    displayName: Package Management
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'Default'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: PowerShell@2
            displayName: 'Install Module Dependencies'
            inputs:
              targetType: 'inline'
              script: |
                # Load the psd1 file so you can read the required modules and install them
                $manifest = Import-PowerShellDataFile .\$(Folder)\*.psd1

                # Install each module
                $manifest.RequiredModules | ForEach-Object { Install-Module -Name $_ -Repository PSGallery -F -Scope CurrentUser }
              workingDirectory: '$(Pipeline.Workspace)/Module'

          - task: PowerShell@2
            displayName: 'Compute Version Number'
            inputs:
              targetType: 'inline'
              script: |
                # Load the psd1 file so you can read the version
                $manifest = Import-PowerShellDataFile .\$(Folder)\*.psd1

                Write-Host "##vso[task.setvariable variable=PACKAGE_VERSION;isOutput=false]$($manifest.ModuleVersion).$(Build.BuildId)"
              workingDirectory: '$(Pipeline.Workspace)/Module'

          - task: PowerShell@2
            displayName: 'Create NuSpec from PSD1'
            inputs:
              targetType: 'inline'
              script: |
                Install-Module -Name Trackyon.Nuget -Scope CurrentUser -Force -Verbose
                ConvertTo-NuSpec -Path ./$(Folder)/VSTeam.psd1
              workingDirectory: '$(Pipeline.Workspace)/Module'

          - task: NuGetCommand@2
            displayName: 'Pack Module'
            inputs:
              command: pack
              packagesToPack: '$(Pipeline.Workspace)/Module/$(Folder)/VSTeam.nuspec'
              packDestination: '$(Pipeline.Workspace)/Module/$(Folder)'
              versioningScheme: byEnvVar
              versionEnvVar: 'PACKAGE_VERSION'

          - task: NuGetCommand@2
            displayName: 'Push Module'
            inputs:
              command: push
              packagesToPush: '$(Pipeline.Workspace)/Module/$(Folder)/*.nupkg'
              publishVstsFeed: 'vsteam'
              allowPackageConflicts: true

- stage: Testing
  displayName: Testing stage
  dependsOn: Package
  jobs:
  
  - template: build/integrationTests.yml
    parameters:
      displayName: 'Linux TFS 2017'
      os: 'Linux'
      name: 'LinuxTFS2017'
      pool: 'ubuntu-latest'
      apiVersion: 'TFS2017'
      depends: 'WindowsTFS2017'
      account: 'http://sonarqube.eastus2.cloudapp.azure.com:8080/tfs/defaultcollection'

  - template: build/integrationTests.yml
    parameters:
      displayName: 'Windows TFS 2017'
      os: 'Windows'
      name: 'WindowsTFS2017'
      pool: 'windows-latest'
      apiVersion: 'TFS2017'
      depends: 'macOSTFS2017'
      account: 'http://sonarqube.eastus2.cloudapp.azure.com:8080/tfs/defaultcollection'

  - template: build/integrationTests.yml
    parameters:
      displayName: 'macOS TFS 2017'
      os: 'macOS'
      pool: 'macOS-latest'
      name: 'macOSTFS2017'
      apiVersion: 'TFS2017'
      account: 'http://sonarqube.eastus2.cloudapp.azure.com:8080/tfs/defaultcollection'

  - template: build/integrationTests.yml
    parameters:
      displayName: 'TFS 2018 Integration Tests'
      os: 'Windows'
      pool: 'windows-latest'
      name: 'windowsTFS2018'
      apiVersion: 'TFS2018'
      account: 'http://168.61.180.150:8080/tfs/defaultcollection'

  - template: build/integrationTests.yml
    parameters:
      displayName: 'AzD Integration Tests'
      os: 'Windows'
      pool: 'windows-latest'
      name: 'windowsAzD'
      apiVersion: 'VSTS'
      account: 'tooltester'

- stage: Produciton
  displayName: PowerShell Gallery
  dependsOn: Testing
  jobs:
  - deployment: Deploy
    displayName: PowerShell Gallery
    pool:
      vmImage: 'windows-latest'
    environment: 'PowerShell Gallery'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo PowerShell Gallery