name: $(Build.BuildID)
resources:
- repo: self

phases:
- phase: Phase_2
  displayName: Linux
  condition: succeeded()
  queue:
    name: Hosted Ubuntu 1604

  steps:
  - powershell: |
       # Load the psd1 file so you can read the required modules and install them
       $manifest = Import-PowerShellDataFile .\*.psd1

       # Install each module
       $manifest.RequiredModules | ForEach-Object { Install-Module -Name $_ -Repository PSGallery -F -Scope CurrentUser }

    displayName: 'Install Dependencies'

  - powershell: 'Install-Module -Name Pester -Repository PSGallery -Force -Scope CurrentUser -AllowClobber -SkipPublisherCheck'

    displayName: 'Install Pester'

  - powershell: |
       Import-Module .\*.psd1
       Invoke-Pester -Script .\unit -EnableExit -Strict -OutputFile test-results.xml -OutputFormat NUnitXml -passthru

    workingDirectory: '$(System.DefaultWorkingDirectory)'
    displayName: 'Run Unit Tests'

  - task: PublishTestResults@2
    displayName: 'Publish Test Results'
    inputs:
      testRunner: NUnit
      testResultsFiles: '**\test-results.xml'
      testRunTitle: 'Linux Unit Tests'
    condition: succeededOrFailed()

- phase: Phase_3
  displayName: MacOS
  condition: succeeded()
  queue:
    name: Hosted macOS

  steps:
  - powershell: |
       # Load the psd1 file so you can read the required modules and install them
       $manifest = Import-PowerShellDataFile .\*.psd1

       # Install each module
       $manifest.RequiredModules | ForEach-Object { Install-Module -Name $_ -Repository PSGallery -F -Scope CurrentUser }

    displayName: 'Install Dependencies'

  - powershell: 'Install-Module -Name Pester -Repository PSGallery -Force -Scope CurrentUser -AllowClobber -SkipPublisherCheck'

    displayName: 'Install Pester'

  - powershell: |
       Import-Module .\*.psd1
       Invoke-Pester -Script .\unit -EnableExit -Strict -OutputFile test-results.xml -OutputFormat NUnitXml -passthru

    workingDirectory: '$(System.DefaultWorkingDirectory)'
    displayName: 'Run Unit Tests'

  - task: PublishTestResults@2
    displayName: 'Publish Test Results'
    inputs:
      testRunner: NUnit
      testResultsFiles: '**\test-results.xml'
      testRunTitle: 'Mac Unit Tests'
    condition: succeededOrFailed()

- phase: Phase_1
  displayName: Windows
  condition: succeeded()
  queue:
    name: Hosted VS2017

  steps:
  - powershell: |
       # Load the psd1 file so you can read the required modules and install them
       $manifest = Import-PowerShellDataFile .\*.psd1

       # Install each module
       $manifest.RequiredModules | ForEach-Object { Install-Module -Name $_ -Repository PSGallery -F -Scope CurrentUser }

    displayName: 'Install Dependencies'

  - powershell: 'Install-Module -Name PSScriptAnalyzer -Repository PSGallery -Force -Scope CurrentUser -Verbose'
    displayName: 'Install PSScriptAnalyzer'

  - powershell: |
       # Has to happen in this task for it to take effect
       # Load the psd1 file so you can read the required modules and import them
       $manifest = Import-PowerShellDataFile .\*.psd1

       # Import each module
       $manifest.RequiredModules | ForEach-Object { Import-Module -Name $_ }

       $r = Invoke-ScriptAnalyzer –Path ./Source –Recurse | Where-Object severity -ne "Information"
       $r | ForEach-Object {Write-Host "##vso[task.logissue type=$($_.Severity);sourcepath=$($_.ScriptPath);linenumber=$($_.Line);columnnumber=$($_.Column);]$($_.Message)"}

    displayName: 'Run Static Code Analysis'

  - powershell: './gen-help.ps1'
    displayName: 'Generate Help'
    workingDirectory: .docs

  - powershell: 'Install-Module -Name Pester -Repository PSGallery -Force -Scope CurrentUser -AllowClobber -SkipPublisherCheck -Verbose'
    displayName: 'Install Pester'

  - powershell: |
       Import-Module .\*.psd1
       Invoke-Pester -Script .\unit -CodeCoverage .\src\*.ps*1 -CodeCoverageOutputFile coverage.xml -CodeCoverageOutputFileFormat JaCoCo -EnableExit -Strict -OutputFile test-results.xml -OutputFormat NUnitXml
    displayName: 'Run Unit Tests'

  - task: PublishTestResults@2
    displayName: 'Publish Test Results'
    inputs:
      testRunner: NUnit
      testResultsFiles: '**\TEST-*.xml'
      testRunTitle: 'Windows Unit Tests'
    condition: succeededOrFailed()

  - task: PublishCodeCoverageResults@1
    displayName: 'Publish code coverage'
    inputs:
      summaryFileLocation: '**\coverage.xml'
      failIfCoverageEmpty: true
    condition: and(succeededOrFailed(), eq(variables['System.PullRequest.IsFork'], false))

  - task: CopyFiles@2
    displayName: 'Copy Module to Artifacts Folder'
    inputs:
      Contents: |
       README.md
       .gitignore
       Source\**

      TargetFolder: '$(build.artifactstagingdirectory)/VSTeam'
    condition: and(succeeded(), eq(variables['System.PullRequest.IsFork'], false))

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Module'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)/VSTeam'
      ArtifactName: Module
    condition: and(succeeded(), eq(variables['System.PullRequest.IsFork'], false))

  - task: CopyFiles@2
    displayName: 'Copy Integration Tests Artifacts Folder'
    inputs:
      Contents: |
       integration\**

      TargetFolder: '$(build.artifactstagingdirectory)/Tests'
    condition: and(succeeded(), eq(variables['System.PullRequest.IsFork'], false))

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Tests'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)/Tests'
      ArtifactName: Test
    condition: and(succeeded(), eq(variables['System.PullRequest.IsFork'], false))